### ISSUE TITLE
Compact identifier

### ISSUE THREAD

**Issue by tmcw** [openlawdc/dc-decoded#17]
For the search index, we need something more compact than normal identifiers. Probably just an index into an ordered list of ids.

**Comment by waldoj** [comment]
I'm not following—could you explain the problem? (Unless you're opening a ticket for a problem you're well on the way to solving, in which case I'll just look at the resulting code. :)

**Comment by tmcw** [comment]
See [search.js](https://github.com/openlawdc/dc-decoded/blob/master/search.js) - it's a slightly modified version of the search indexer I wrote for the dcmr project, and works all right here - full search index was 8.8mb and brought down to 7.8mb by adding 30 top-frequency stopwords. Wil do some more word analysis to see if we can cut the top 100 or so on. But the files being produced are large because they have lots of large strings at the moment - gzip will bring this down, but not enough - here's the [index for z, for example](https://gist.github.com/tmcw/5372585).

**Comment by waldoj** [comment]
Ah, got it. FWIW, v0.9 of The State Decoded ([under active development now](https://github.com/o19s/statedecoded)) will have support for Solr/ElasticSearch/CloudSearch baked in. Solr support is already deployed in Virginia Decoded—if you have some interest in Solr, I'm happy to share the config files with you. OTOH, there's a lot to be said for using what already works for you. :)

**Comment by tmcw** [comment]
Quick word frequency: https://docs.google.com/a/macwright.org/spreadsheet/ccc?key=0AoVvhLurSlaHdFhwZTREOS1fMFh0R0hTRXV5aG9GeHc#gid=1

I've had some experience with solr/sphinx/elasticsearch and will keep the possibility open, but will try my best to avoid requiring them - they've been headaches in a number of ways unfortunately,

**Comment by waldoj** [comment]
Solr is, unfortunately, a pain in the ass. It makes me want to throw things. But it's also a brilliant program. And that's why I'm baking it into The State Decoded—so that people have to think about it as little as possible in order to implement it, ideally not at all beyond `apt-get solr`. The ability to perform automated linguistic analysis (e.g., "list more laws like this one") is just so wonderful that I can't really pass it up. :) OTOH, I've found Sphinx very, very easy to work with, although it's not nearly as powerful or flexible as Solr.

Here's a quick word frequency list for the Virginia Code:

```
1               8656
2               6925
3               5470
4               4040
person          9172
commonwealth    8645
chapter         8217
provisions      7923
section         7759
pursuant        7485
state           7409
board           6560
required        6407
law             6086
time            5871
ii              5760
public          5549
court           5363
department      4991
subject         4973
including       4851
virginia        4632
subsection      4621
provide         4539
authorized      4390
purposes        4375
order           4374
general         4374
title           4254
property        4240
commission      4185
act             4167
article         4030
thereof         3981
accordance      3973
authority       3853
date            3812
services        3794
days            3784
county          3763
seq             3713
purpose         3672
interest        3641
issued          3621
business        3587
notice          3548
amount          3508
paid            3487
apply           3473
include         3453
```

In case any of those might be useful noisewords for D.C., but missing from your list.

**Comment by tmcw** [comment]
> The ability to perform automated linguistic analysis (e.g., "list more laws like this one") is just so wonderful that I can't really pass it up.

You could just do topic clustering statically :)

**Comment by tmcw** [comment]
First shot at a compact index in 28fef28ac1d56df4fec06fab88e968848da9d1f2 - this halves the total index size and per-letter indexes are now quite small https://gist.github.com/tmcw/5372896

**Comment by waldoj** [comment]
I could, but it's really facilitating other people doing interesting things that I'm looking to do. For instance, supporting Solr makes it a lot easier to support Mahout, because of Lucene's term vector functionality, and I'd love to see what people do with legal data with Mahout! Lucene/Solr is a platform with a lot of existing support, and, at least for my work, I find it really helpful to be able to plug into that existing infrastructure. Of course, I'm looking to facilitate a lot of different use cases and a lot of different implementors, while in your case, you're the implementor and you know just how you're using it! :)
