### ISSUE TITLE
Fix parser death

### ISSUE THREAD

**Issue by tmcw** [openlawdc/dc-decoded#20]
In progress: https://github.com/openlawdc/dc-decoded/tree/update

[Tokenizer](https://github.com/Floby/node-tokenizer) is quietly exiting before the end of the code.

**Comment by vdavez** [comment]
Tom--After looking at the data a while, I have some suggestions about how to parse. Essentially, looks like you can divide it from Division->Title->Chapter->Unit->Subchapter->Part-Subpart->Section->(Text + History).
If you subdivide in that hierarchy, you should be able to get it to just the section level... I think in the prior iteration, you may have missed the "Unit" subdivision, because it's not always there...
Also, there's an exception to the Regex for Title 28 (Uniform Commercial Code). Somewhere I wrote a Regex that captures both the usual and the Title 28, but I can't find it.
Hope this helps. I'm so excited to see you back on this!

**Comment by tmcw** [comment]
Cool! At this point just grappling with technical issues, but I'll make sure to add tests & make this a more robust parser than before.
