### ISSUE TITLE
Produce Markdown from JSON

### ISSUE THREAD

**Issue by tmcw** [openlawdc/dc-decoded#8]
Ideally we can produce a common form of Markdown that's useful for [Pandoc](http://johnmacfarlane.net/pandoc/) as well as just GitHub, Jekyll, and other common markdown systems.

**Comment by waldoj** [comment]
Is it links that you're looking to store as Markdown? If not, might plain text suffice? I'm on the go right now, but IIRC, the DC Code has no formatting to speak of.

**Comment by tmcw** [comment]
> Is it links that you're looking to store as Markdown? If not, might plain text suffice? I'm on the go right now, but IIRC, the DC Code has no formatting to speak of.

Links, lists, and headings - ideally a markdown export would make this easier to read in systems that support markdown, and headings would provide some minimal structure that could produce, for instance, automatic TOC in LaTeX after conversion w/ Pandoc.

**Comment by konklone** [comment]
I have a laughably alpha example of Markdown I did on an earlier digital version of the DC Code, with the render Ruby snippet included:

https://gist.github.com/konklone/5326841

Having the DC Code get reasonably formatted within Github itself, not to mention lots of Jekyll-based systems, is useful and neat. Especially if some day people want to try the new-laws-as-diffs approach with the DC Code.

**Comment by waldoj** [comment]
The decision will need to be made about whether the text of each law is a list. On the one hand, it is, in that most laws are divided into subsections. On the other hand, it's not, in what Markdown sees as a list, since it cannot represent nested, labelled hierarchies as HTML can.

FWIW, [this is a feature under development for The State Decoded](https://github.com/statedecoded/statedecoded/issues/161). I'm considering using AsciiDoc there. That feature should be implemented in 30–45 days.

**Comment by tmcw** [comment]
-> https://github.com/openlawdc/formats
